### PR TITLE
Print form parameters when sayAndMakeRequest(Request)

### PR DESCRIPTION
**Pull request by sparkoo**

### CODE REVIEW

**Comment by raphaelbauer** [comment]
That's pretty and perfect! Could you add your change to changelog.md... Then I'll merge it asap... Thanks!

**Comment by raphaelbauer** [comment]
Very nice! Thanks! I'll cut a new minor release asap..

**Comment by raphaelbauer** [comment]
1.1.6 has been released... cheers...!

**Comment by sparkoo** [comment]
cool, thanks. when you think it will be in ninja release?

**Comment by raphaelbauer** [comment]
You can speed things up by incrementing the doctester version at Ninja's pom.xml, adding your change to the changelog and submitting a PR :)

**Pull request merged**
